name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: husain-python-lesson
      REGION: asia-southeast2
      REPO_NAME: github-action

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      # 2. Install gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}

      # 3. Verify gcloud
      - name: Verify gcloud
        run: gcloud info

      # 4. Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # 5. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      # 6. Tag & Push to Artifact Registry (latest + commit SHA)
      - name: Push to Artifact Registry
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE_URI_BASE=$REGION-docker.pkg.dev/${{ vars.PROJECT_ID }}/$REPO_NAME/$IMAGE_NAME
          
          echo "Pushing image as latest and commit SHA: $COMMIT_SHA"
          
          # Tag with latest
          docker tag $IMAGE_NAME:latest $IMAGE_URI_BASE:latest
          docker push $IMAGE_URI_BASE:latest
          
          # Tag with commit SHA
          docker tag $IMAGE_NAME:latest $IMAGE_URI_BASE:$COMMIT_SHA
          docker push $IMAGE_URI_BASE:$COMMIT_SHA
