---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: husain-python-lesson
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      # 2. Install gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}
          install_components: 'beta'

      # 3. Verify gcloud
      - name: verify gcloud
        run: gcloud info

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
